package cc.moecraft.school.database.model.base;

import io.jboot.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserProfiles<M extends BaseUserProfiles<M>> extends JbootModel<M> implements IBean {

	public void setGoogleSub(java.lang.String googleSub) {
		set("google_sub", googleSub);
	}
	
	public java.lang.String getGoogleSub() {
		return getStr("google_sub");
	}

	public void setGradingProfile(java.lang.String gradingProfile) {
		set("grading_profile", gradingProfile);
	}
	
	public java.lang.String getGradingProfile() {
		return getStr("grading_profile");
	}

	public void setStudentProfile(java.lang.String studentProfile) {
		set("student_profile", studentProfile);
	}
	
	public java.lang.String getStudentProfile() {
		return getStr("student_profile");
	}

}
