package cc.moecraft.school.database.model.base;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.JbootModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTimeMap<M extends BaseTimeMap<M>> extends JbootModel<M> implements IBean {

	public void setIndex(java.lang.Integer index) {
		set("index", index);
	}
	
	public java.lang.Integer getIndex() {
		return getInt("index");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setGrades(java.lang.String grades) {
		set("grades", grades);
	}
	
	public java.lang.String getGrades() {
		return getStr("grades");
	}

	public void setGradeAverage(java.lang.Double gradeAverage) {
		set("grade_average", gradeAverage);
	}
	
	public java.lang.Double getGradeAverage() {
		return getDouble("grade_average");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public void setAdder(java.lang.String adder) {
		set("adder", adder);
	}
	
	public java.lang.String getAdder() {
		return getStr("adder");
	}

}
