package cc.moecraft.school.database.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProfiles<M extends BaseProfiles<M>> extends Model<M> implements IBean {

	public void setGoogle-sub(java.lang.String google-sub) {
		set("google-sub", google-sub);
	}
	
	public java.lang.String getGoogle-sub() {
		return getStr("google-sub");
	}

	public void setGrading-profile(java.lang.String grading-profile) {
		set("grading-profile", grading-profile);
	}
	
	public java.lang.String getGrading-profile() {
		return getStr("grading-profile");
	}

	public void setStudent-profile(java.lang.String student-profile) {
		set("student-profile", student-profile);
	}
	
	public java.lang.String getStudent-profile() {
		return getStr("student-profile");
	}

}
