package cc.moecraft.school.database.model;

import cc.moecraft.school.database.model.base.BaseProfiles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Profiles extends BaseProfiles<Profiles> {
	
}
