package cc.moecraft.school.database.model;

import cc.moecraft.school.database.model.base.BaseTimeMap;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TimeMap extends BaseTimeMap<TimeMap> {
	
}
