package cc.moecraft.school.database.model;

import cc.moecraft.school.database.model.base.BaseUserInfo;
import cc.moecraft.school.profile.grading.GradingProfile;
import cc.moecraft.school.profile.student.StudentProfile;

import static cc.moecraft.school.Constants.GSON;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfo extends BaseUserInfo<UserInfo>
{
    /**
     * Get student profile as an object.
     *
     * @return Student profile.
     */
    public StudentProfile getStudentProfileObject()
    {
        return GSON.fromJson(getStudentProfile(), StudentProfile.class);
    }

    /**
     * Get grading profile as an object.
     *
     * @return Grading profile.
     */
    public GradingProfile getGradingProfileObject()
    {
        return GSON.fromJson(getGradingProfile(), GradingProfile.class);
    }
}
