package cc.moecraft.school.database.model;

import cc.moecraft.school.database.model.base.BaseUserProfiles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserProfiles extends BaseUserProfiles<UserProfiles> {
	
}
