package cc.moecraft.school.database.model;

import cc.moecraft.school.database.model.base.BaseUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfo extends BaseUserInfo<UserInfo> {
	
}
